### ISSUE TITLE
Require reset keypress for System76 Launch

### ISSUE THREAD

**Issue by jackpot51** [fwupd/fwupd#2935]
Right now it resets with a HID command. For security reasons, we want to verify physical access to the keyboard before it can reset to the bootloader. I want to implement this, and I know other plugins do it with some kind of prompt to the user. What is the best example I can look at?

**Comment by hughsie** [comment]
The only thing we have similar are devices like 8bitdo controllers that require you to unplug the controller, hold down a few buttons and replug the controller. There's also the altos ChaosKey, Pinecil and AIAIAI devices which you have to hold down a button on insert to get them into a bootloader that you can query. In the case of the Pinecil there's no USB runtime at all which makes it more of a challenge.

I guess it depends on what you want to do. The easiest thing would be to ask the user to hold down a button while plugging in, and if they do that the "canDownload" bit in the DFU runtime interface gets set to 1, rather than 0. You could obviously implement something else for a custom HID protocol.

There's https://lvfs.readthedocs.io/en/latest/metainfo.html#screenshots to read for that kind of thing; the way that works in fwupd is that the device sets FU_DEVICE_REMOVE_DELAY_USER_REPLUG and FWUPD_DEVICE_FLAG_NEEDS_BOOTLOADER which causes the front end to fwupd to download the URL and show the user an image with a screenshot and caption.

The firmware has to "require" a GUI that can show an image, if it can't work with just a caption: https://lvfs.readthedocs.io/en/latest/metainfo.html#client-features -- the lineart should probably match the style of the existing ones.

Of course, with my security hat on you should probably just require signed firmware images, which means even if the system is compromised you can't flash an unsigned malicious payload onto the keyboard even if you auto-boot it into DFU mode. I personally like the Google Chromebook way of doing this, where you have a signed requirement on firmware, unless you remove the physical screw on the motherboard (voiding your warranty in the process) -- but of course this requires a keyboard controller that's powerful enough to do meaningful crypto, or an ECC/RSA accelerator chip.
