### ISSUE TITLE
Encrypted swap file reported as Unencrypted by HSI

### ISSUE THREAD

**Issue by dnoliver** [fwupd/fwupd#3342]
**Describe the bug**

Ubuntu 20.04 uses PLAIN swap files by default. I set up the swap file encryption as follow:

Create a swap file:

```
dd if=/dev/zero of=/cryptswap bs=1M count=512 status=progress
```

Update `/etc/crypttab` so it gets a random key and a mapper:

```
echo "cryptswap /cryptswap /dev/urandom swap,cipher=aes-xts-plain64,size=256" >> /etc/crypttab
```

Configure swap in mapper:

```
mkswap /dev/mapper/cryptswap
```

And use it:

```
swapon /dev/mapper/cryptswap
```

``fwupdtool security --force` still say my swap in not encrypted

**Steps to Reproduce**
Steps to reproduce the behavior.

More or less explained above

**Expected behavior**

Swap should be reported as encrypted (AFAIK, I ma configuring my swap encryption correctly, but you never know!)

**fwupd version information**
Please provide the version of the daemon and client.
```shell
root@ubuntu:~/fwupd/build/src# fwupdmgr --version
client version: 1.6.0-104-gf4e8bec0
compile-time dependency versions
        gusb:   0.3.7

daemon version: 1.6.0-104-gf4e8bec0
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

From source, latest main branch

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
root@ubuntu:~/fwupd/build/src# fwupdmgr get-devices --show-all-devices
WARNING: UEFI capsule updates not available or enabled in firmware setup
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
WARNING: This package has not been validated, it may not work properly.
Virtual Machine
│
├─Intel(R) Core™ i7-8665U CPU @ 1.90GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0xffffffff
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                         30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│                         561403e8-143a-5071-ab09-bf5e4c146983 ← CPUID\PRO_0&FAM_06&MOD_8E
│                         d5092916-1868-5182-8c70-12f83dab6372 ← CPUID\PRO_0&FAM_06&MOD_8E&STP_C
│     Device Flags:       • Internal device
│
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Summary:            Microsoft Virtual TPM 2.0
│ │   Current version:    8213.275.21.18466
│ │   Vendor:             Microsoft (TPM:MSFT)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│ │                       2a65d4b6-60a0-5e8c-acfa-d86cc3cbe4c3 ← TPM\VEN_MSFT&DEV_0001
│ │                       f4acf73a-7e07-5e66-83a0-732e90dd57a6 ← TPM\VEN_MSFT&MOD_IoTSoftwareTPM
│ │                       5bea8d58-c840-513e-a5ad-0184cbaa9821 ← TPM\VEN_MSFT&DEV_0001&VER_2.0
│ │                       898fcede-e30b-5722-b9d2-25cf14d2917e ← TPM\VEN_MSFT&MOD_IoTSoftwareTPM&VER_2.0
│ │   Device Flags:       • Internal device
│ │
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff ← system-tpm-eventlog
│       Device Flags:     • Internal device
│
└─UEFI dbx:
      Device ID:          362301da643102b9f38477387e2193e57abaa590
      Summary:            UEFI Revocation Database
      Current version:    77
      Minimum Version:    77
      Vendor:             UEFI:Linux Foundation
      Install Duration:   1 second
      GUIDs:              c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
                          f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
      Device Flags:       • Internal device
                          • Updatable
                          • Needs a reboot after installation
```

**Additional questions**
- Operating system and version: Ubuntu 20.04 on Microsoft Hyper-V (Test system)
- Have you tried rebooting? Yes
- Is this a regression? Don't know

By adding a couple of `g_debug` statements, I got the reason why it is being taken as uncrypted

```diff
diff --git a/libfwupdplugin/fu-volume.c b/libfwupdplugin/fu-volume.c
index 01af28d7..86731759 100644
--- a/libfwupdplugin/fu-volume.c
+++ b/libfwupdplugin/fu-volume.c
@@ -263,13 +263,22 @@ fu_volume_is_encrypted (FuVolume *self)

        g_return_val_if_fail (FU_IS_VOLUME (self), FALSE);

-       if (self->proxy_blk == NULL)
+        g_debug("WE ARE HERE");
+
+       if (self->proxy_blk == NULL) {
+               g_debug("Con 1");
                return FALSE;
+       }
        val = g_dbus_proxy_get_cached_property (self->proxy_blk, "CryptoBackingDevice");
-       if (val == NULL)
+       if (val == NULL) {
+               g_debug("Con 2");
                return FALSE;
-       if (g_strcmp0 (g_variant_get_string (val, NULL), "/") == 0)
+       }
+       if (g_strcmp0 (g_variant_get_string (val, NULL), "/") == 0) {
+               g_debug(g_variant_get_string (val, NULL));
+               g_debug("Con 3");
                return FALSE;
+       }
        return TRUE;
 }
```

And I get this in the verbose log:

```
19:32:31:0080 FuPlugin             add_security_attrs(linux_swap)
19:32:31:0101 FuVolume             WE ARE HERE
19:32:31:0101 FuVolume             /
19:32:31:0101 FuVolume             Con 3
19:32:31:0101 FuPluginLinuxSwap    /dev/dm-2 partition is unencrypted
```

Not sure if that helps and sorry for subpar debugging capabilities!

**Comment by wagnux** [comment]
Still reproducible on a current system. Same class of issue as this one (plain dm-crypt swap, not LUKS), just documenting a fresh, fully working example for the record.

**Environment**
- Distro: Ubuntu 26.04 LTS
- Kernel: 7.0.0-27-generic
- fwupd: 2.1.1
- Motherboard: Gigabyte B550M AORUS ELITE

**Setup**

Swap is a file-backed dm-crypt "plain" volume with a random per-boot key, configured the standard way via crypttab/fstab (this is the documented approach for swap-only encryption, e.g. Arch wiki "Swap encryption", and doesn't use LUKS headers on purpose, since the key is ephemeral).

`/etc/crypttab`:
```
swap_crypt /swap_container /dev/urandom swap,cipher=aes-xts-plain64,size=256,offset=1024,discard
```

`/etc/fstab`:
```
/dev/mapper/swap_crypt none swap sw 0 0
```

`swapon --show`:
```
NAME      TYPE      SIZE USED PRIO
/dev/dm-0 partition   8G   0B   -1
```

`dmsetup table swap_crypt`:
```
0 16776192 crypt aes-xts-plain64 0000000000000000000000000000000000000000000000000000000000000000 0 7:38 1024 1 allow_discards
```

`cat /sys/block/dm-0/dm/uuid`:
```
CRYPT-PLAIN-swap_crypt
```

**Result**

`fwupdmgr security` reports:
```
✘ Swap do Linux: Descriptografado
```
(i.e. "Linux swap: Unencrypted")

**Expected behavior**

The `org.fwupd.hsi.Kernel.Swap` check should recognize a dm-crypt device backing the active swap entry regardless of whether it was formatted with a LUKS header, since `CRYPT-PLAIN-*` is a legitimate and arguably *more* appropriate encryption mode for swap specifically (random key each boot, no header to attack, no passphrase to leak via history/scripts). It looks like the detector may only be matching on a `CRYPT-LUKS1-`/`CRYPT-LUKS2-` prefix in `dm/uuid`, which would explain why plain-mode dm-crypt swap (the setup actually recommended by most distro wikis for swap-only encryption) is flagged as unencrypted, while a full-disk-LUKS setup with swap merely riding along inside it (per #4969, #5123, #6407) has the opposite problem — actually protected but not detected because the swap file/partition itself isn't directly on a `CRYPT-LUKS*` device.

Happy to test a patch or provide more debug output if useful.

**Comment by hughsie** [comment]
> Still reproducible on a current system

Even with 2.1.6? If that version doesn't detect this, a PR would be very welcome.
