### ISSUE TITLE
json-glib version too old in snap package of 1.7.3

### ISSUE THREAD

**Issue by PhilippWendler** [fwupd/fwupd#4099]
**Describe the bug**
`fwupdmgr security --force` from snap outputs the following message instead of the desired output:
```
WARNING: This package has not been validated, it may not work properly.
json-glib version too old
```

**Steps to Reproduce**
```
sudo fwupd.fwupdmgr security --force
```

**Expected behavior**
The snap package should bundle the library in the required version such that all features of fwupd work.

**fwupd version information**
1.7.3 (snap package `fwupd` from `richard-hughes`)
Same problem with the `1.7.3-30-gdb94a995` version from the `--edge` snap.

**fwupd device information**
I don't think this is relevant here, if you still require it I will post it.

**Additional questions**

- Operating system and version: *Ubuntu 21.10*
- Have you tried rebooting? *no*
- Is this a regression? *Yes, when installing 1.6.2 with the `--candidate` snap it works.*

**Comment by superm1** [comment]
The snap is built from core18 (Ubuntu 18.04 archives), so it grabs json-glib 1.4.2, but as of https://github.com/fwupd/fwupd/commit/dbdd3740a34f8de07ec3a988308ce8ea9c4f3508 it's not a 1.6.0 dependency.

Even bumping up to core20 that won't help the situation as it's still 1.4.4.  So I think the only way to get around this would be to pull a newer json-glib as part of the snap build process instead of the one from the Ubuntu archives.
