### ISSUE TITLE
After fwupd-main of T99W373 device, the carrier config seem to be not expected

### ISSUE THREAD

**Issue by Fanice-luo** [fwupd/fwupd#6274]
Describe the question
When I use .cab to update/downgrade T99W373 device, finished with "Successfully installed firmware", but sometimes the carrier config seem to be not expected(GCF, DF, CC are all possible).

Wrong situation 1:

![1](https://github.com/fwupd/fwupd/assets/114575316/84ef1d36-d007-4f16-9ded-07b2e5cf6447)

Wrong situation 2:

![2](https://github.com/fwupd/fwupd/assets/114575316/ccb90d08-6a66-4312-8bde-e4b12fce7f21)

But when I modify fu-mm-decvice.c of g_timeout_add_seconds(20, fu_mm_device_get_firmware_version_mbim_timeout, &ctx)
all will be expected.Could you offer me some advice?
![3](https://github.com/fwupd/fwupd/assets/114575316/796d7e9c-0da4-469e-9274-b650f4805367)

Best wishes, Fanice

**Comment by hughsie** [comment]
> But when I modify fu-mm-decvice.c of g_timeout_add_seconds(20, fu_mm_device_get_firmware_version_mbim_timeout, &ctx) all will be expected

That seems like a sensible thing to do. Could we make it something like 30 seconds?

**Comment by Fanice-luo** [comment]
I'm afraid 30s is too long, because sometimes the expected carrier config can also be obtained at 10s. But the probability is extremely low.

**Comment by Fanice-luo** [comment]
Hi @aleksander0m What would cause inconsistency between MM's carrier config and fwupd's carrier config? How should I debug it?

**Comment by Fanice-luo** [comment]
Hi @hughsie For fu_mm_device_get_firmware_version_mbim_timeout is 10s, mbim-proxy log can MCFG MCFG switching sequence  is DF, GC, CMCC,here is something from mbim-proxy log.
![4](https://github.com/fwupd/fwupd/assets/114575316/3dc80498-6b67-4813-b128-9fff88da8fef)

And  fu_mm_device_get_firmware_version_mbim_timeout is 20s, it switching CMCC directly.
![5](https://github.com/fwupd/fwupd/assets/114575316/e2428ac6-1d47-4e6c-a8c4-24ae7377814f)

**Comment by aleksander0m** [comment]
> Hi @aleksander0m What would cause inconsistency between MM's carrier config and fwupd's carrier config? How should I debug it?

What is the inconsistency here? Is the fwupd plugin loading one firmware version that is different to the one loaded by MM? Can you elaborate?

The "GC" carrier config is the one the device would boot with if there is no other carrier specific configuration. The "CC" carrier config would be the one associate to the CMCC operator.

ModemManager has built-in support to automatically select carrier config (using QMI PDC) whenever the SIM card operator code is read. Once this happens, the modem object is removed and it is reprobed from scratch once the new carrier config has been selected. We did this for older Foxconn models, e.g. the DW5821e and others. I don´t think we added MM-triggered automatic carrier selection for the T99W373, although I may be mistaken.

Another possibility could be that it is the modem itself switching carrier config automatically, and so it depends when you query the firmware version and you may or may not get the latest carrier config reported. If this is happening, we have a problem, because right now ModemManager does not listen to notifications reporting automatic carrier config switches (don´t even know if they are being notified at all).

Could you elaborate a bit what is happening here?

**Comment by SlarkXiao** [comment]
Hi @aleksander0m ,
Yes, you are right. T99W373(SDX65) and T99W175(SDX55) won't call the MM-triggered automatic carrier selection since we did it in firmware side. But now, just like you said, the problem is we may not get the latest carrier config from device side if the time slot is not proper. 
So do we have any fix mechanism (like a retry) if the carrier is "DF" or "GC"?  AFAIK, this switch may take no more than 5 seconds from DF(->GC)->CC.

**Comment by aleksander0m** [comment]
No, this is not solved with retrying to reload, or at least that is not what I would recommend to do in the first attempt.

If the module is switching carrier config internally, is that notified to the host in any way? Maybe the modem can send a specific QMI PDC indication when the switch happens, and MM could monitor that?

MM should re-probe the device completely whenever a carrier config switch is detected.

**Comment by SlarkXiao** [comment]
We just get feedback from our internal team, and they said the client needs to register the indication by QMI_PDC_INDICATION_REGISTER , then they will receive the indication of QMI_PDC_CONFIG_CHANGE_IND.
So if we want to implement this, shall we add 2 QMI message in libqmi?

**Comment by SlarkXiao** [comment]
@aleksander0m As I said in last, I think that solution may also don't work even if we register this indication in ModemManager side. We can't ensure that this register point would be earlier than the MCFG switch point in last boot.
We may have 2 situation as below:
a. fwupd 1st reboot->fwupd 2nd reboot->MM initial->register PDC indication->MCFG switch in firmware side->received PDC indication->MM re-probe
b. fwupd 1st reboot->fwupd 2nd reboot->MM initial->MCFG switch in firmware side->register PDC indication  //MCFG mismatch still exist
Do you have any idea?

**Comment by kerixi781** [comment]
> Yes, you are right. T99W373(SDX65) and T99W175(SDX55) won't call the MM-triggered automatic carrier selection since we did it in firmware side. But now, just like you said, the problem is we may not get the latest carrier config from device side if the time slot is not proper.
> So do we have any fix mechanism (like a retry) if the carrier is "DF" or "GC"? AFAIK, this switch may take no more than 5 seconds from DF(->GC)->CC.

You on the wrong way. New famely 5G card have SDX65 and SDX62, its mean T99W368 - SDX65, T99W373 - SDX62!!!
