### ISSUE TITLE
fwupd unusable when waiting for device unplug

### ISSUE THREAD

**Issue by mcrha** [fwupd/fwupd#6526]
I have installed fwupd-1.9.2-1.fc38.x86_64 . I installed a "Device firmware" update in gnome-software, while it crashed at the end of the install ( https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1837 ). The fwupd daemon was still in the "waiting for device unplug" state (according to the backtrace I did not save, unfortunately).

The fwupd does not respond to basic requests when waiting for the device unplug, like when I send the machine to reboot. I've been watching 3 minutes "down-count" during the reboot of the machine before systemd gave up and killed the daemon service.

I'd say the daemon should be able to recover in some way while waiting for a device unplug, as for me is easier to restart the machine than to unplug Thunderbolt. There would help to respond to the reboot request at least. Having returned errors when in the waiting state will be also appreciated.

Side question: is there a way for the gnome-software to recognize the "waiting for unplug" state straight after a fresh start of the gnome-software? I know there's a signal for this (where gnome-software crashed), but when I start gnome-software again the signal is long gone, while fwupd daemon is still waiting.

Also, how much necessary the unplug is? I can download/install other firmware updates not touching this device without unplugging it, no?

**Comment by hughsie** [comment]
I think we mitigated some of this problem in b60ddcf496a5b118d414ab3d86b09a91f47eff0b -- which is in fwupd 1.9.10 and newer.  I think we also need to unset the `FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG` in more cases, but in the event the interactive request to the user failed (because the client was dead) we should now return with an error _before getting to_ `FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG` -- so the install will "fail" but we don't block shutdown.
